cors:
  allow_any_origin: true

health_check:
  listen: "127.0.0.1:8088"
  enabled: false

supergraph:
  path: /
  defer_support: true
  introspection: true
sandbox:
  enabled: true
homepage:
  enabled: false
subscription:
  enabled: true
  mode:
    passthrough:
      all:
        path: /ws
headers:
  all:
    request:
      - propagate:
          named: "player"

include_subgraph_errors:
  all: true

telemetry:
  experimental_logging:
    format: pretty
    display_filename: true
    display_line_number: true
    # when_header:
    #   - name: "origin"
    #     match: ".*"
    #     headers: false
    #     body: true
